### ISSUE TITLE
for .. of loop does not work

### ISSUE THREAD

**Issue by JPeer264** [gruntjs/grunt-contrib-uglify#354]
Hey folks,

I have a `for .. of` loop in my .js files. But if I want to uglify those files all I got is an error message like
```shell
message: 'Unexpected token name «of», expected punc «;»',
```
Somebody has same issues?

**META**
```shell
stack: 'Error\n    at new JS_Parse_Error (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)    
at js_error (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:204:11)
at croak (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:684:41)
at token_error (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:688:9)
at expect_token (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:701:9)
at expect (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:704:36)
at regular_for (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:934:9)
at for_ (/PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:930:16)
at PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:812:24
at /PATHS/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:727:24' }
```

**Comment by avdg** [comment]
There is no harmony support on uglifyjs2's side on npm just yet. See https://github.com/mishoo/UglifyJS2/issues/448 if you want to track status
