### ISSUE TITLE
SyntaxError: Unexpected token name «of», expected punc «;».

### ISSUE THREAD

**Issue by ColinHuang** [gruntjs/grunt-contrib-uglify#452]
I have write code in my js file.
```
for (name of list) {
  do something
}
```
it will failed with `Warning: Uglification failed.
SyntaxError: Unexpected token name «of», expected punc «;». 
`

grunt-contrib-uglify version: 2.1.0

**Comment by XhmikosR** [comment]
This is an upstream issue, please it there.

**Comment by xavadu** [comment]
What it means that is a upstream issue?

**Comment by XhmikosR** [comment]
It means, it's an issue with uglify-js and not this plugin.

**Comment by xavadu** [comment]
oh! I see, grunt-contrib-uglify is using uglify-js.
I hope that they add support for ES6 soon. Thanks.

**Comment by XhmikosR** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/421#issuecomment-290525091

**Comment by samson-sham** [comment]
When using `grunt-contrib-uglify@3.3.0`
```
{ [SyntaxError: Unexpected token name «of», expected punc «;»
  at JS_Parse_Error.get (<anonymous>:73:23)
  at formatError (util.js:802:16)
  at formatValue (util.js:615:14)
  at inspect (util.js:328:10)
  at Object.formatWithOptions (util.js:182:12)
  at Console.(anonymous function) (console.js:188:15)
  at Console.log (console.js:199:31)
  at /Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt-contrib-uglify/tasks/uglify.js:144:17
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt-contrib-uglify/tasks/uglify.js:78:16)
  at Object.<anonymous> (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/grunt/task.js:252:15)
  at Object.thisTask.fn (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/util/task.js:293:12)
  at /Applications/mampstack-7.1.15-0/apache2/htdocs/xxx/node_modules/grunt/lib/util/task.js:220:11
  at process._tickCallback (internal/process/next_tick.js:61:11)
]
```
Still upstream issue?

**Comment by XhmikosR** [comment]
Obviously. You are using ES6 code.

**Comment by samson-sham** [comment]
@XhmikosR 
Oh, since I followed the GitHub link from grunt-contrib-uglify-es NPM to here, hence I thought 3.3.0 has updated to use ES6.
Now I see the branch `harmony`. Solved. Thanks for the reply.
