### ISSUE TITLE
Cannot read property 'transform' of null

### ISSUE THREAD

**Issue by romero83** [gruntjs/grunt-contrib-uglify#456]
Hi!

NodeJS version: 7.6.0
NPM: 4.1.2
Grunt-contrib-uglify: 2.2.0

Uglyfing a Browserified JS file.

```
Running "uglify:modeler" (uglify) task
TypeError: Cannot read property 'transform' of null
  at eval (<anonymous>:3053:24)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3147:21)
  at AST_Call.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3136:49)
  at AST_VarDef.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3131:28)
  at AST_Var.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3142:21)
  at AST_Function.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3147:21)
  at AST_Call.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3151:29)
  at AST_Seq.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3096:49)
  at AST_Return.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3142:21)
  at AST_Function.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3170:33)
  at AST_Assign.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3152:29)
  at AST_Seq.eval [as transform] (<anonymous>:3038:21)
  at eval (<anonymous>:3065:31)
  at AST_SimpleStatement.eval [as transform] (<anonymous>:3038:21)
  at collapse_single_use_vars (<anonymous>:5698:30)
  at tighten_body (<anonymous>:5632:30)
  at eval (<anonymous>:6799:21)
  at AST_Function.eval [as optimize] (<anonymous>:5447:23)
  at Compressor.before (<anonymous>:5430:21)
  at AST_Function.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3146:43)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Call.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3065:31)
  at Compressor.before (<anonymous>:5429:9)
  at AST_SimpleStatement.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3142:21)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Function.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3180:25)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Array.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3188:33)
  at Compressor.before (<anonymous>:5429:9)
  at AST_ObjectKeyVal.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3184:27)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Object.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3147:21)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Call.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3065:31)
  at Compressor.before (<anonymous>:5429:9)
  at AST_SimpleStatement.eval [as transform] (<anonymous>:3034:35)
  at eval (<anonymous>:3053:25)
  at doit (<anonymous>:139:23)
  at MAP (<anonymous>:165:52)
  at do_list (<anonymous>:3052:16)
  at eval (<anonymous>:3069:21)
  at Compressor.before (<anonymous>:5429:9)
  at AST_Toplevel.eval [as transform] (<anonymous>:3034:35)
  at Compressor.compress (<anonymous>:5405:25)
  at Object.exports.minify (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt-contrib-uglify\tasks\lib\uglify.js:101:29)
  at c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt-contrib-uglify\tasks\uglify.js:156:25
  at Array.forEach (native)
  at Object.<anonymous> (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt-contrib-uglify\tasks\uglify.js:77:16)
  at Object.<anonymous> (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\grunt\task.js:255:15)
  at Object.thisTask.fn (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.<anonymous> (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\util\task.js:293:12)
  at c:\workspaces\cl2\gitrepo\decision-modeler_bugfix\decision-modeler\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

>> Uglifying source target/dist/index.js failed.
Warning: Uglification failed.
Cannot read property 'transform' of null.
 Use --force to continue.

Aborted due to warnings.
```

**Additional information: It works with Grunt-contrib-uglify version 2.1.0**

**Comment by XhmikosR** [comment]
Try again after deleting your local node_modules and reinstalling them. It probably is an upstream issue.
