### ISSUE TITLE
SyntaxError: Unexpected token: name (ChargingStationClient)

### ISSUE THREAD

**Issue by LucasBrazi06** [gruntjs/grunt-contrib-uglify#469]
Hi,

I'm trying to uglify a nodejs project and got an unexpected syntax error:

```
Running "uglify:files" (uglify) task
{ SyntaxError: Unexpected token: name (ChargingStationClient)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Data\Private\Innovation\EV\ev-server\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
    at formatError (util.js:648:15)
    at formatValue (util.js:553:18)
    at inspect (util.js:186:10)
    at exports.format (util.js:72:24)
    at Console.log (console.js:43:37)
    at C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt-contrib-uglify\tasks\uglify.js:150:17
    at Array.forEach (native)
    at Object.<anonymous> (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt-contrib-uglify\tasks\uglify.js:76:16)
    at Object.<anonymous> (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\grunt\task.js:255:15)
    at Object.thisTask.fn (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\grunt\task.js:73:16)
    at Object.<anonymous> (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\util\task.js:294:30)
    at Task.runTaskFn (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\util\task.js:244:24)
    at Task.<anonymous> (C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\util\task.js:293:12)
    at C:\Data\Private\Innovation\EV\ev-server\node_modules\grunt\lib\util\task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Unexpected token: name (ChargingStationClient)',
  filename: 'src/client/ChargingStationClient.js',
  line: 1,
  col: 6,
  pos: 6 }
```
But this module is a simple class declaration:
```
class ChargingStationClient {
  constructor() {
  }
}
```

Here are the option I used in grunt:

```
uglify: {
    files: ["src/**/*.js"],
    options: {
         beautify: false, //prod
    output: {
         comments: false
    },
    mangle: {
         screw_ie8: true
    }, //prod
    compress: {
          screw_ie8: true,
          warnings: false,
          conditionals: true,
          unused: true,
          comparisons: true,
          sequences: true,
          dead_code: true,
          evaluate: true,
          if_return: true,
          join_vars: true,
          negate_iife: false // we need this for lazy v8
    },
    comments: false //prod
}
```
Thanks,
Serge.

**Comment by slig** [comment]
FWIW, Uglify doesn't not support the newer ES6 syntax. See https://github.com/mishoo/UglifyJS2/issues/448
