### ISSUE TITLE
can't beautify the ES6?

### ISSUE THREAD

**Issue by DXkite** [gruntjs/grunt-contrib-uglify#495]
**config**
```js
 uglify: {
            options: {
                banner: '/*! <%= pkg.name %> by <%= pkg.author %> <%= grunt.template.today("yyyy-mm-dd") %> */\n'
            },
            build: {
                src: 'dxui/<%= pkg.name %>.js',
                dest: 'dxui/<%= pkg.name %>.min.js'
            }
}
```

**script**
```js
'use strict';
let someValue='value';

class SomeClass {
    
}
```

**console**
```
{ SyntaxError: Unexpected token: name (someValue)
  at JS_Parse_Error.get (<anonymous>:79:23)
  at formatError (util.js:646:15)
  at formatValue (util.js:552:18)
  at inspect (util.js:185:10)
  at exports.format (util.js:71:24)
  at Console.log (console.js:43:37)
  at D:\WorkSpace\Javascript\dxui\node_modules\grunt-contrib-uglify\tasks\uglify.js:144:17
  at Array.forEach (native)
  at Object.<anonymous> (D:\WorkSpace\Javascript\dxui\node_modules\grunt-contrib-uglify\tasks\uglify.js:78:16)
  at Object.<anonymous> (D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\grunt\task.js:255:15)
  at Object.thisTask.fn (D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\grunt\task.js:73:16)
  at Object.<anonymous> (D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\util\task.js:293:12)
  at D:\WorkSpace\Javascript\dxui\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:389:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:502:3

  message: 'Unexpected token: name (someValue)',
  filename: 'dxui.js',
  line: 2,
  col: 4,
  pos: 19 }
>> Uglifying source dxui/dxui.js failed.
```

version:  3.1.0

**Comment by alexlamsl** [comment]
https://github.com/gruntjs/grunt-contrib-uglify/issues/482#issuecomment-312860523
