### ISSUE TITLE
Maximum call stack size exceeded error with 4.0.1

### ISSUE THREAD

**Issue by tankist** [gruntjs/grunt-contrib-uglify#537]
Version 4.0.1 is failing on minification:
```
at AST_Node.eval [as is_boolean] (<anonymous>:7516:30)
  at AST_Node.eval [as is_boolean] (<anonymous>:7536:35)
  at AST_Node.eval [as is_boolean] (<anonymous>:7516:30)
  at AST_Node.eval [as is_boolean] (<anonymous>:7536:35)
  at AST_Node.eval [as is_boolean] (<anonymous>:7516:30)
  at AST_Node.eval [as is_boolean] (<anonymous>:7536:35)
  at AST_Node.eval [as is_boolean] (<anonymous>:7516:30)
  at AST_Node.eval [as is_boolean] (<anonymous>:7536:35)
  at AST_Node.eval [as is_boolean] (<anonymous>:7516:30)
  at eval (<anonymous>:10667:54)
  at AST_Node.eval [as optimize] (<anonymous>:11794:19)
  at Object.before (<anonymous>:5421:24)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:3040:33)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2943:25)
  at doit (<anonymous>:122:23)
  at MAP (<anonymous>:148:52)
  at do_list (<anonymous>:2942:16)
  at eval (<anonymous>:3026:28)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2953:31)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2943:25)
  at doit (<anonymous>:122:23)
  at MAP (<anonymous>:148:52)
  at do_list (<anonymous>:2942:16)
  at eval (<anonymous>:3019:21)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:3040:33)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2943:25)
  at doit (<anonymous>:122:23)
  at MAP (<anonymous>:148:52)
  at do_list (<anonymous>:2942:16)
  at eval (<anonymous>:3026:28)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2953:31)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2943:25)
  at doit (<anonymous>:122:23)
  at MAP (<anonymous>:148:52)
  at do_list (<anonymous>:2942:16)
  at eval (<anonymous>:3019:21)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:3029:43)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:3022:43)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2953:31)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at eval (<anonymous>:2943:25)
  at doit (<anonymous>:122:23)
  at MAP (<anonymous>:148:52)
  at do_list (<anonymous>:2942:16)
  at eval (<anonymous>:2956:21)
  at Object.before (<anonymous>:5416:9)
  at AST_Node.eval [as transform] (<anonymous>:3060:31)
  at Object.compress (<anonymous>:5362:25)
  at Object.minify (<anonymous>:12943:75)
  at Object.exports.minify (/home/circleci/myproject/node_modules/grunt-contrib-uglify/tasks/lib/uglify.js:124:27)
  at /home/circleci/myproject/node_modules/grunt-contrib-uglify/tasks/uglify.js:142:25
  at Array.forEach (native)
  at Object.<anonymous> (/home/circleci/myproject/node_modules/grunt-contrib-uglify/tasks/uglify.js:78:16)
  at Object.<anonymous> (/home/circleci/myproject/node_modules/grunt/lib/grunt/task.js:252:15)
  at Object.thisTask.fn (/home/circleci/myproject/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/home/circleci/myproject/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/home/circleci/myproject/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/home/circleci/myproject/node_modules/grunt/lib/util/task.js:293:12)
  at /home/circleci/myproject/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)

>> Uglifying source ../public/minified/js/script.early.js failed.
Warning: Uglification failed.
Maximum call stack size exceeded. 
 Use --force to continue.

Aborted due to warnings.
Exited with code 6
```

Version 4.0.0 works fine on the same fileset

Node.js v6.9.5

**Comment by alexlamsl** [comment]
Please report this to https://github.com/mishoo/UglifyJS2 instead.
